/**
 * RecommendationPanel — Explains AI recommendation confidence breakdown.
 *
 * Wraps the existing ConfidenceMeter data into ExplainPanel format.
 * Reuses reasons/caveats/confidence from aiService responses.
 * No new AI logic created.
 */

import React from 'react';
import { ExplainPanel, type ExplainFactor, type FactorStatus } from './ExplainPanel';
import { Sparkles, Target, CheckCircle2, AlertTriangle, Database, Search } from 'lucide-react';

interface RecommendationPanelProps {
  /** 0-100 confidence percentage from AI response */
  confidencePct: number;
  /** Positive reasons from AI (why recommended) */
  reasons: string[];
  /** Caveats from AI (things to consider) */
  caveats?: string[];
  /** Evidence sources used by RAG (from ai response data) */
  evidenceSources?: string[];
  /** Query the user asked (used in subtitle) */
  query?: string;
  inline?: boolean;
}

export function RecommendationPanel({
  confidencePct,
  reasons,
  caveats = [],
  evidenceSources = [],
  query,
  inline = false,
}: RecommendationPanelProps) {

  // Confidence tier
  const confStatus: FactorStatus = confidencePct >= 80 ? 'positive' : confidencePct >= 60 ? 'warning' : 'neutral';

  const factors: ExplainFactor[] = [
    // AI Confidence
    {
      icon: <Sparkles className="w-3.5 h-3.5" />,
      label: 'AI Confidence Score',
      value: `${confidencePct}%`,
      status: confStatus,
      explanation: confidencePct >= 80
        ? 'High confidence — strong signal alignment across multiple data sources.'
        : confidencePct >= 60
        ? 'Moderate confidence — recommendation is data-backed but some uncertainty exists.'
        : 'Low confidence — insufficient data. Apply additional due diligence.',
      progress: confidencePct,
    },

    // Positive reasons
    ...reasons.slice(0, 4).map((reason, idx) => ({
      icon: <CheckCircle2 className="w-3.5 h-3.5" />,
      label: `Positive Signal ${idx + 1}`,
      value: '✓',
      status: 'positive' as FactorStatus,
      explanation: reason,
    })),

    // Caveats
    ...caveats.slice(0, 2).map((caveat, idx) => ({
      icon: <AlertTriangle className="w-3.5 h-3.5" />,
      label: `Consideration ${idx + 1}`,
      value: '⚠',
      status: 'warning' as FactorStatus,
      explanation: caveat,
    })),

    // Evidence sources
    ...(evidenceSources.length > 0 ? [{
      icon: <Database className="w-3.5 h-3.5" />,
      label: 'Knowledge Sources Used',
      value: `${evidenceSources.length} docs`,
      status: 'info' as FactorStatus,
      explanation: evidenceSources.join(' · '),
    }] : []),

    // RAG quality indicator
    {
      icon: <Search className="w-3.5 h-3.5" />,
      label: 'RAG Context Retrieved',
      value: evidenceSources.length > 0 ? 'Yes' : 'Standard',
      status: evidenceSources.length > 0 ? 'positive' : 'neutral',
      explanation: evidenceSources.length > 0
        ? 'Recommendation grounded in AssetChain knowledge base and live platform data.'
        : 'General knowledge base consulted. Platform-specific context may be limited.',
    },
  ];

  return (
    <ExplainPanel
      triggerLabel="Recommendation"
      title="Recommendation Breakdown"
      subtitle={query ? `For: "${query.slice(0, 60)}${query.length > 60 ? '…' : ''}"` : 'AI decision factors'}
      factors={factors}
      score={`${confidencePct}% Confidence`}
      scoreColor={confStatus === 'positive' ? 'text-emerald-400' : confStatus === 'warning' ? 'text-amber-400' : 'text-slate-400'}
      inline={inline}
      disclaimer="AI recommendations are generated by AssetChain Copilot using RAG over live platform data. Every recommendation explains Why, Confidence %, Risks, Positive factors, and Negative factors. The AI Advisor operates strictly as a read-only advisory model and CANNOT execute transactions."
    />
  );
}
